---
deployment:
  tasks:
    - export DEPLOYPATH=/home/laravelbaseproject/
    - /bin/rm -rf $DEPLOYPATH/app
    - /bin/rm -rf $DEPLOYPATH/bootstrap
    - /bin/rm -rf $DEPLOYPATH/config
    - /bin/rm -rf $DEPLOYPATH/resources
    - /bin/rm -rf $DEPLOYPATH/routes
    - /bin/rm -rf $DEPLOYPATH/vendor
    - /bin/rm -rf $DEPLOYPATH/storage/app/public/*
    - /bin/rm -rf $DEPLOYPATH/storage/framework/cache/*
    - /bin/rm -rf $DEPLOYPATH/storage/framework/sessions/*
    - /bin/rm -rf $DEPLOYPATH/storage/framework/views/*
    - /bin/rm -rf $DEPLOYPATH/public_html
    - /bin/cp -R public_html $DEPLOYPATH
    - /bin/rm -rf $DEPLOYPATH/public_html/cdn.*
    - /bin/cp -R scripts/production/.htaccess $DEPLOYPATH/public_html/
    - /bin/cp -R app $DEPLOYPATH
    - /bin/cp -R bootstrap $DEPLOYPATH
    - /bin/cp -R config $DEPLOYPATH
    - /bin/cp -R resources $DEPLOYPATH
    - /bin/cp -R routes $DEPLOYPATH
    - /bin/cp -R vendor $DEPLOYPATH
